
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADICIONAR COLORIR CONTAINER CRIAR FECHAR_CONTAINER NUMERO PARA STRING TAMANHO TELA TEXTO X comandos : comando\n                | comandos comando  comando : CRIAR TELA NUMERO X NUMERO comando : ADICIONAR TEXTO STRING comando : COLORIR TEXTO STRING PARA STRING  comando : CRIAR CONTAINER NUMERO X NUMERO comando : FECHAR_CONTAINER'
    
_lr_action_items = {'CRIAR':([0,1,2,6,7,14,19,20,21,],[3,3,-1,-7,-2,-4,-3,-6,-5,]),'ADICIONAR':([0,1,2,6,7,14,19,20,21,],[4,4,-1,-7,-2,-4,-3,-6,-5,]),'COLORIR':([0,1,2,6,7,14,19,20,21,],[5,5,-1,-7,-2,-4,-3,-6,-5,]),'FECHAR_CONTAINER':([0,1,2,6,7,14,19,20,21,],[6,6,-1,-7,-2,-4,-3,-6,-5,]),'$end':([1,2,6,7,14,19,20,21,],[0,-1,-7,-2,-4,-3,-6,-5,]),'TELA':([3,],[8,]),'CONTAINER':([3,],[9,]),'TEXTO':([4,5,],[10,11,]),'NUMERO':([8,9,16,17,],[12,13,19,20,]),'STRING':([10,11,18,],[14,15,21,]),'X':([12,13,],[16,17,]),'PARA':([15,],[18,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'comandos':([0,],[1,]),'comando':([0,1,],[2,7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> comandos","S'",1,None,None,None),
  ('comandos -> comando','comandos',1,'p_comandos','comandos.py',8),
  ('comandos -> comandos comando','comandos',2,'p_comandos','comandos.py',9),
  ('comando -> CRIAR TELA NUMERO X NUMERO','comando',5,'p_comando_tela','comandos.py',13),
  ('comando -> ADICIONAR TEXTO STRING','comando',3,'p_comando_texto','comandos.py',21),
  ('comando -> COLORIR TEXTO STRING PARA STRING','comando',5,'p_comando_colorir_texto','comandos.py',29),
  ('comando -> CRIAR CONTAINER NUMERO X NUMERO','comando',5,'p_comando_container','comandos.py',36),
  ('comando -> FECHAR_CONTAINER','comando',1,'p_fechar_container','comandos.py',43),
]
