
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ALINHAMENTO BOTAO CABECALHO IMAGEM NUMERO STRING TAMANHO TELA TEXTOcomandos : comando\n                | comandos comandocomando : TELA NUMERO NUMEROcomando : CABECALHO STRING TAMANHO ALINHAMENTOcomando : BOTAO STRING NUMERO NUMEROcomando : IMAGEM STRING NUMERO NUMEROcomando : TEXTO STRING TAMANHO ALINHAMENTO'
    
_lr_action_items = {'TELA':([0,1,2,8,14,19,20,21,22,],[3,3,-1,-2,-3,-4,-5,-6,-7,]),'CABECALHO':([0,1,2,8,14,19,20,21,22,],[4,4,-1,-2,-3,-4,-5,-6,-7,]),'BOTAO':([0,1,2,8,14,19,20,21,22,],[5,5,-1,-2,-3,-4,-5,-6,-7,]),'IMAGEM':([0,1,2,8,14,19,20,21,22,],[6,6,-1,-2,-3,-4,-5,-6,-7,]),'TEXTO':([0,1,2,8,14,19,20,21,22,],[7,7,-1,-2,-3,-4,-5,-6,-7,]),'$end':([1,2,8,14,19,20,21,22,],[0,-1,-2,-3,-4,-5,-6,-7,]),'NUMERO':([3,9,11,12,16,17,],[9,14,16,17,20,21,]),'STRING':([4,5,6,7,],[10,11,12,13,]),'TAMANHO':([10,13,],[15,18,]),'ALINHAMENTO':([15,18,],[19,22,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'comandos':([0,],[1,]),'comando':([0,1,],[2,8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> comandos","S'",1,None,None,None),
  ('comandos -> comando','comandos',1,'p_comandos','main.py',45),
  ('comandos -> comandos comando','comandos',2,'p_comandos','main.py',46),
  ('comando -> TELA NUMERO NUMERO','comando',3,'p_comando_tela','main.py',49),
  ('comando -> CABECALHO STRING TAMANHO ALINHAMENTO','comando',4,'p_comando_cabecalho','main.py',55),
  ('comando -> BOTAO STRING NUMERO NUMERO','comando',4,'p_comando_botao','main.py',63),
  ('comando -> IMAGEM STRING NUMERO NUMERO','comando',4,'p_comando_imagem','main.py',69),
  ('comando -> TEXTO STRING TAMANHO ALINHAMENTO','comando',4,'p_comando_texto','main.py',75),
]
